name: Trigger auto deployment for microtwitter

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/microtwitter-AutoDeployTrigger-09c1b8e2-6081-4bae-93a4-9a3b6e7c392f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.MICROTWITTER_REGISTRY_USERNAME }}
          password: ${{ secrets.MICROTWITTER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 4722794/microtwitter:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MICROTWITTER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n microtwitter -g microtwitter_group --server docker.io --username  ${{ secrets.MICROTWITTER_REGISTRY_USERNAME }} --password ${{ secrets.MICROTWITTER_REGISTRY_PASSWORD }}
            az containerapp update -n microtwitter -g microtwitter_group --image 4722794/microtwitter:${{ github.sha }}
